[Wording] Changer pin en code d'accès
betagouv/conferences pull request #66
Opened 2020-11-06 10:23 UTC by jdauphant

2020-11-06 10:34 UTC, astranchet requested changes
Je ne vois pas où s'affiche ce texte 🤔

2020-11-06 10:34 UTC, astranchet commented on views/confCreated.ejs
> +            **** (Vous avez reçu le code d'accès par email, si vous l'avez perdu, annuler cette conférence et générer une nouvelle conférence)
"Vous avez reçu le code d'accès par email, si vous l'avez perdu, annulez cette conférence et démarrez en une nouvelle"

(correction de faute d'orthographe et utilisation de "démarrer" plutôt que "générer"

2020-11-06 18:02 UTC, jdauphant commented on views/confCreated.ejs
> +            **** (Vous avez reçu le code d'accès par email, si vous l'avez perdu, annuler cette conférence et générer une nouvelle conférence)
```suggestion
            **** (Vous avez reçu le code d'accès par email, si vous l'avez perdu, annuler cette conférence et démarrer une nouvelle conférence)
```

2020-11-06 18:02 UTC, jdauphant commented
> Je ne vois pas où s'affiche ce texte

@astranchet c'est affiché si tu supprimes le code ~pin~d'accès de l'url de la conférence

2020-11-09 07:58 UTC, astranchet approved these changes

2020-11-09 12:51 UTC, merged